stages:
  - lint

# Линтинг с flake8, isort и black
lint:
  stage: lint
  image: python:3.10
  script:
    - flake8 --max-line-length=79 .
    - isort --check-only --diff .
    - black --check --diff .