stages:      
  - linting

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose --line-length=79 .

flake8:   
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/test.txt
    - flake8 .

job:
  stage: linting
  image: python:3.10
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/prod.txt
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test
