stages:
  - lint
  - test

# Проверка кода с помощью flake8
lint:
  stage: lint
  image: python:3.10
  before_script:
    - pip install flake8 flake8-bugbear flake8-quotes python-dotenv
  script:
    - flake8 --max-line-length=79 .

# Запуск тестов с использованием pytest
test:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements/prod.txt
    - pip install pytest
  script:
    - pytest --maxfail=1 --disable-warnings -q