stages:      
  - linting
  - test

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose --line-length=80 .

flake8:   
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --inline-quotes 'double' .

django-tests:
  stage: test
  script:
    - python3 /lyceum/manage.py test
