variables:
  SECRET_KEY: 'bugagaga'
  DEBUG: 'True'
  ALLOWED_HOSTS: '.example.com,.anotherhost.com,127.0.0.1'

stages:      
  - linting
  - test

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose --line-length=80 .

flake8:   
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --inline-quotes 'double' .

django-tests:
  stage: test
  image: python:3.12

  script:
    - pip install -r requirements/test.txt
    - python3 lyceum/manage.py test
