stages:      
  - linting

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose --line-length=80 .

flake8:   
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/test.txt
    - flake8 .

django-tests:
  stage: linting
  image: python:3.12
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/prod.txt
    - pip install -r requirements/test.txt
    - python lyceum/manage.py test
