# Generated by Django 4.2.16 on 2024-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя пользователя",
                        max_length=100,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Название товара",
                        max_length=500,
                        verbose_name="Описание сообщения",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Адрес электронной почты",
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
            },
        ),
    ]
