# Generated by Django 4.2.16 on 2024-11-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина 100 символов",
                        max_length=100,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Максимальная длина 500 символов",
                        max_length=500,
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="дата и время создания",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Введите корректный адрес электронной почты",
                        max_length=254,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
            },
        ),
        migrations.DeleteModel(
            name="FeedbackModel",
        ),
    ]
