# Generated by Django 4.2.16 on 2024-11-03 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0003_feedback_status_statuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Максимальная длина 100 символов",
                max_length=100,
                null=True,
                verbose_name="Имя пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
                verbose_name="Обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
