# Generated by Django 4.2.16 on 2024-11-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "feedback",
            "0005_remove_feedback_mail_remove_feedback_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Максимальная длина 100 символов",
                        max_length=100,
                        null=True,
                        verbose_name="имя пользователя",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        help_text="Введите корректный адрес электронной почты",
                        max_length=254,
                        verbose_name="адрес электронной почты",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль пользователя",
                "verbose_name_plural": "профили пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackfile",
            options={
                "verbose_name": "файл обратной связи",
                "verbose_name_plural": "файлы обратных связей",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "получено"),
                    ("in_progress", "в обработке"),
                    ("done", "ответ дан"),
                ],
                default="new",
                help_text="может быть трёх видов: «получено», «в обработке» и «ответ дан»",
                max_length=11,
                verbose_name="статус сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.CharField(
                help_text="Максимальная длина 500 символов",
                max_length=500,
                verbose_name="текст сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=feedback.models.FeedbackFile.get_upload_path,
                verbose_name="файл обратной связи",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="feedback",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="feedback.feedback",
                verbose_name="обратная связь",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="status_from",
            field=models.CharField(
                choices=[
                    ("new", "получено"),
                    ("in_progress", "в обработке"),
                    ("done", "ответ дан"),
                ],
                db_column="from",
                max_length=11,
                verbose_name="перешел из состояния",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="status_to",
            field=models.CharField(
                choices=[
                    ("new", "получено"),
                    ("in_progress", "в обработке"),
                    ("done", "ответ дан"),
                ],
                db_column="to",
                max_length=11,
                verbose_name="перешел в состояние",
            ),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.AddField(
            model_name="feedbackuserprofile",
            name="author",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="feedback.feedback",
                verbose_name="профиль пользователя",
            ),
        ),
    ]
