# Generated by Django 4.2.16 on 2024-11-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="attempts_count",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
