# Generated by Django 4.2.16 on 2024-11-11 13:20

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
