# Generated by Django 4.2.16 on 2024-11-13 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="customuser",
            name="attempts_count",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "proxy": False,
            },
            bases=("users.customuser",),
        ),
        migrations.AlterField(
            model_name="Profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="пользователь",
            ),
        ),
    ]
