# Generated by Django 4.2.16 on 2024-11-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_attempts_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="attempts_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
