# Generated by Django 4.2.16 on 2024-11-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_user_customuser_attempts_count_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
    ]
