# Generated by Django 4.2.9 on 2024-10-21 18:09

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(
                        upload_to="items/gallery/"
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="MainImage",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                help_text="Основная крупная картинка товара, связь 1:1",
                null=True,
                upload_to="items/main/",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="items",
                to="catalog.image",
                verbose_name="дополнительные изображения",
            ),
        ),
    ]
