# Generated by Django 4.2.9 on 2024-10-14 19:17

import django.core.validators
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcategory",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[catalog.models.validate_slug],
            ),
        ),
        migrations.AlterField(
            model_name="catalogcategory",
            name="weight",
            field=models.PositiveIntegerField(
                default=100,
                validators=[django.core.validators.MaxValueValidator(32767)],
            ),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[catalog.models.validate_slug],
            ),
        ),
    ]
