# Generated by Django 4.2.9 on 2024-10-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_catalogcategory_is_published_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CatalogCategory",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="CatalogItem",
            new_name="Item",
        ),
        migrations.RenameModel(
            old_name="CatalogTag",
            new_name="Tag",
        ),
    ]
