# Generated by Django 4.2.9 on 2024-10-22 09:51

import catalog.validators
import ckeditor.fields
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_item_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to="items/gallery/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Обязательно нужно использовать слова роскошно или превосходно",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание товара",
            ),
        ),
    ]
