# Generated by Django 4.2.9 on 2024-10-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_image_image_alter_item_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="MainImage",
            new_name="main_image",
        ),
    ]
