# Generated by Django 4.2.16 on 2024-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_gallery_mainimage_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="нормализованное имя",
            ),
        ),
    ]
