# Generated by Django 4.2.16 on 2024-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_normalized_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="Отображение на главной стнарице"
            ),
        ),
    ]
