# Generated by Django 4.2.16 on 2024-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_item_is_on_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Используйте только буквы, цифры, '-', '_'. Не должно быть пустым.",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Используйте только буквы, цифры, '-', '_'. Не должно быть пустым.",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
